import React from 'react';

interface HelpModalProps {
  isOpen: boolean;
  onClose: () => void;
  isDark: boolean;
}

export default function HelpModal({ isOpen, onClose, isDark }: HelpModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className={`relative w-full max-w-2xl max-h-[85vh] overflow-y-auto border shadow-2xl p-8 rounded-none ${isDark ? 'bg-[#0c0c0e] border-zinc-700 text-zinc-300' : 'bg-white border-zinc-300 text-zinc-700'}`}>
        <button 
          onClick={onClose}
          title="Close Guide"
          className="font-bold text-xl absolute top-6 right-4 text-zinc-400 dark:text-zinc-500 hover:text-red-500 dark:hover:text-red-400 px-2 py-1 text-sm hover:bg-zinc-50 dark:hover:bg-zinc-900 border border-transparent hover:border-red-200 dark:hover:border-red-900/60 rounded-none transition-all font-sans cursor-pointer"
        >
          ✕
        </button>
        
        <h2 className="text-2xl font-bold uppercase tracking-wider mb-6 text-zinc-900 dark:text-white border-b border-zinc-200 dark:border-zinc-800 pb-4">
          Visualizer Features Guide
        </h2>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h3 className="text-orange-600 dark:text-orange-400 font-bold uppercase tracking-wide mb-2">File Management</h3>
            <p>Drag and drop prologue JSON files generated by the Rizin <code className="font-mono bg-zinc-100 dark:bg-zinc-800 px-1 py-0.5 border border-zinc-200 dark:border-zinc-700">pg</code> plugin. You can load multiple trees simultaneously and swap between them under the <b>FILES</b> tab.</p>
          </section>

          <section>
            <h3 className="text-orange-600 dark:text-orange-400 font-bold uppercase tracking-wide mb-2">Heatmap Analysis</h3>
            <p>Nodes are automatically colored based on their traffic frequency relative to the root node. In the <b>TOOLS</b> tab, you can toggle the heatmap ON/OFF and choose between professional data science color palettes (Rocket, Mako, Viridis). Max frequency nodes are dark, while minimum frequency nodes are light.</p>
          </section>

          <section>
            <h3 className="text-orange-600 dark:text-orange-400 font-bold uppercase tracking-wide mb-2">Path Highlighting</h3>
            <p>In the <b>TOOLS</b> tab, enter a sequence of hex bytes (e.g. <code className="font-mono bg-zinc-100 dark:bg-zinc-800 px-1 py-0.5 border border-zinc-200 dark:border-zinc-700">55 48 89</code>) to instantly highlight matching execution paths across the tree in bright orange.</p>
          </section>

          <section>
            <h3 className="text-orange-600 dark:text-orange-400 font-bold uppercase tracking-wide mb-2">Node Inspector</h3>
            <p>Click on Inspector tab and then click on any circular byte node to open the <b>INSPECTOR</b> tab. Here you can view exact byte values (Hex/Bits), hit counts, and precise branching traffic percentages relative to the root node and immediate parent.</p>
          </section>

          <section>
            <h3 className="text-orange-600 dark:text-orange-400 font-bold uppercase tracking-wide mb-2">Optimization</h3>
            <p>For extremely large datasets, use the <b>Tree Depth</b> slider in the TOOLS tab to restrict rendering depth and drastically improve browser performance.</p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-zinc-200 dark:border-zinc-800 text-center text-xs text-zinc-500 dark:text-zinc-600 font-mono">
          rz-prelude-visualizer
        </div>
      </div>
    </div>
  );
}
